#!/bin/bash
# Build entrypoint. Generates src/lib/git-sha.ts (gitignored) so
# build-version.ts has the SHA at runtime without spawning git.
set -euo pipefail
cd "$(dirname "$0")/.."

if [[ -n "${GIT_SHA:-}" ]]; then
  SHA="${GIT_SHA}"
else
  SHA="$(git rev-parse --short=12 HEAD 2>/dev/null || echo unknown)"
  if [[ "${SHA}" != "unknown" ]] && ! git diff-index --quiet HEAD -- 2>/dev/null; then
    SHA="${SHA}-dirty"
  fi
fi

cat > src/lib/git-sha.ts <<EOF
// AUTO-GENERATED by scripts/build.sh — do not edit by hand. Gitignored.
export const GIT_SHA = '${SHA}';
EOF

echo "[build] GIT_SHA=${SHA}"
exec pnpm exec tsc -p tsconfig.json
