version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    labels: [ "deps" ]
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      production:
        dependency-type: "production"
        update-types: [ "patch", "minor" ]
      development:
        dependency-type: "development"
        update-types: [ "patch", "minor" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    labels: [ "deps", "ci" ]
    commit-message:
      prefix: "ci(deps)"
