"""Emit valid STD-002 blocks (templates).

The `bbe-comm emit <type>` subcommand uses this module. It is also called by
self-test code to produce a self-validating result block.

Templates are intentionally minimal — they include the REQUIRED fields per
@type with placeholder values. Values that the operator-side CLI generates
(IDs, nonces, HMAC) are placeholders for emit; sign via `bbe-block sign auth`
to obtain a valid HMAC-anchored auth block.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from ..constants import PROTOCOL_VERSION


def _now_id_compact() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")


def emit(block_type: str, *, label: str | None = None,
         correlation_id: str | None = None,
         agent: str | None = None,
         parent_id: str | None = None) -> str:
    """Return a template block for `block_type` with the given hints.

    Hints are NOT validated — the caller is responsible for filling them
    correctly. This is for human review / paste / sign workflow.
    """
    if block_type == "operator_prompt":
        lbl = label or "OPERATOR-PROMPT"
        cid = correlation_id or "<correlation-id>"
        return (
            f"[{lbl}]\n"
            f"@bbe-comm: {PROTOCOL_VERSION}\n"
            f"@type: operator_prompt\n"
            f"@id: op_prompt_{_now_id_compact()}_<hex8>\n"
            f"@correlation_id: {cid}\n\n"
            f"<task description>\n"
            f"[/{lbl}]\n"
        )
    if block_type == "operator_auth":
        lbl = label or "OPERATOR-AUTH"
        cid = correlation_id or "<correlation-id>"
        return (
            f"[{lbl}]\n"
            f"@bbe-comm: {PROTOCOL_VERSION}\n"
            f"@type: operator_auth\n"
            f"@id: <generated by `bbe-block sign auth`>\n"
            + (f"@parent_id: {parent_id}\n" if parent_id else "")
            + f"@correlation_id: {cid}\n"
            f"@scope: [\"<scope-token>\"]\n"
            f"@target: <target>\n"
            f"@ttl: 5m\n"
            f"@issued_by: <operator>\n"
            f"@nonce: <generated>\n"
            f"@hmac: sha256:<generated>\n\n"
            f"<optional note>\n"
            f"[/{lbl}]\n"
        )
    if block_type == "operator_deny":
        lbl = label or "OPERATOR-DENY"
        cid = correlation_id or "<correlation-id>"
        return (
            f"[{lbl}]\n"
            f"@bbe-comm: {PROTOCOL_VERSION}\n"
            f"@type: operator_deny\n"
            f"@id: <generated by `bbe-block sign deny`>\n"
            f"@correlation_id: {cid}\n"
            f"@revokes: <id-of-operator_auth-being-revoked>\n"
            f"@nonce: <generated>\n"
            f"@hmac: sha256:<generated>\n"
            f"@reason: <why-revoking>\n"
            f"[/{lbl}]\n"
        )
    if block_type == "agent_query":
        lbl = label or "AGENT-QUERY"
        cid = correlation_id or "<correlation-id>"
        ag  = agent or "<type>@<version>@<host>"
        return (
            f"[{lbl}]\n"
            f"@bbe-comm: {PROTOCOL_VERSION}\n"
            f"@type: agent_query\n"
            f"@id: agent_query_{_now_id_compact()}_<hex8>\n"
            + (f"@parent_id: {parent_id}\n" if parent_id else "")
            + f"@correlation_id: {cid}\n"
            f"@agent: {ag}\n"
            f"@ask: <one-line question>\n"
            f"@compliance_level: L4\n"
            f"[/{lbl}]\n"
        )
    if block_type == "agent_result":
        lbl = label or "AGENT-RESULT"
        cid = correlation_id or "<correlation-id>"
        ag  = agent or "<type>@<version>@<host>"
        return (
            f"[{lbl}]\n"
            f"@bbe-comm: {PROTOCOL_VERSION}\n"
            f"@type: agent_result\n"
            f"@id: agent_result_{_now_id_compact()}_<hex8>\n"
            + (f"@parent_id: {parent_id}\n" if parent_id else "")
            + f"@correlation_id: {cid}\n"
            f"@agent: {ag}\n"
            f"@status: complete\n"
            f"@compliance_level: L4\n\n"
            f"<body — what was done, evidence>\n"
            f"[/{lbl}]\n"
        )
    if block_type == "agent_abort":
        lbl = label or "AGENT-ABORT"
        cid = correlation_id or "<correlation-id>"
        ag  = agent or "<type>@<version>@<host>"
        return (
            f"[{lbl}]\n"
            f"@bbe-comm: {PROTOCOL_VERSION}\n"
            f"@type: agent_abort\n"
            f"@id: agent_abort_{_now_id_compact()}_<hex8>\n"
            + (f"@parent_id: {parent_id}\n" if parent_id else "")
            + f"@correlation_id: {cid}\n"
            f"@agent: {ag}\n"
            f"@reason: <kebab-case reason>\n"
            f"@compliance_level: L4\n\n"
            f"<context — why halting>\n"
            f"[/{lbl}]\n"
        )
    raise ValueError(
        f"unknown block_type: {block_type!r}; supported: "
        f"operator_prompt, operator_auth, operator_deny, agent_query, "
        f"agent_result, agent_abort"
    )
