-- Author: <fill at first run>
-- Date:   <fill at first run>
-- Commit: bootstrap from api-standards/templates/service-skeleton/_optional/auth
-- ============================================================
-- __SERVICE_NAME__ — auth layer.
--
-- This migration is **opt-in** for services that authenticate callers
-- with their own bearer-token registry (as opposed to inheriting auth
-- from a sibling service). It is generated by:
--
--   bash new-service.sh ... --with-auth --token-prefix=<2-4 lowercase letters>
--
-- The opt-in carries three tables:
--   * __DB_SCHEMA__.api_keys      — argon2id-hashed token registry
--   * __DB_SCHEMA__.auth_failures — cluster-wide brute-force counter
--   * __DB_SCHEMA__.outbox        — transactional event outbox (consumed by hooks)
--
-- Token layout: __TOKEN_PREFIX___<key_id 26 chars base32>_<secret 43 chars base64url>
--   key_id     — public, indexable lookup id (no secret material)
--   key_hash   — argon2id(secret); secret is never persisted
--   public_id  — UUIDv7; used as actor_id in audit events
--
-- Scopes are free-form TEXT[]. Convention: 'admin', 'write', 'read'.
-- Service-specific scopes get added in a follow-up migration if needed.
-- ============================================================

-- ---- api_keys ------------------------------------------------
CREATE TABLE IF NOT EXISTS __DB_SCHEMA__.api_keys (
  id            BIGSERIAL PRIMARY KEY,
  public_id     UUID NOT NULL UNIQUE,
  key_id        TEXT NOT NULL UNIQUE,
  key_hash      TEXT NOT NULL,
  name          TEXT NOT NULL,
  owner         TEXT NOT NULL,
  scopes        TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  expires_at    TIMESTAMPTZ,
  last_used_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at    TIMESTAMPTZ
);

COMMENT ON TABLE  __DB_SCHEMA__.api_keys IS
  'API keys for __SERVICE_NAME__. key_hash is argon2id(secret). Token = "__TOKEN_PREFIX___"||key_id||"_"||secret.';
COMMENT ON COLUMN __DB_SCHEMA__.api_keys.public_id IS
  'UUIDv7. Used as actor_id in audit events for human-traceable provenance.';
COMMENT ON COLUMN __DB_SCHEMA__.api_keys.scopes IS
  'Required scopes (admin, write, read; service-specific extensions allowed).';

-- Hot path: verify lookup by key_id, ignoring revoked rows.
CREATE INDEX IF NOT EXISTS api_keys_active
  ON __DB_SCHEMA__.api_keys (key_id)
  WHERE revoked_at IS NULL;

-- ---- auth_failures (brute-force counter) ---------------------
-- One row per (bucket_kind, bucket_value).
-- bucket_kind ∈ {'key_id','ip'}. The two buckets are OR-combined in
-- application code: either trip-wire fires the 429.
CREATE TABLE IF NOT EXISTS __DB_SCHEMA__.auth_failures (
  bucket_kind   TEXT NOT NULL CHECK (bucket_kind IN ('key_id','ip')),
  bucket_value  TEXT NOT NULL,
  fails         INT  NOT NULL DEFAULT 1,
  first_fail_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (bucket_kind, bucket_value)
);

COMMENT ON TABLE __DB_SCHEMA__.auth_failures IS
  'Cluster-wide brute-force counter. fails resets to 1 once first_fail_at is older than 60s.';

-- Sweeper purge index (covers WHERE first_fail_at < now() - interval '60 seconds').
CREATE INDEX IF NOT EXISTS auth_failures_first_fail_at
  ON __DB_SCHEMA__.auth_failures (first_fail_at);

-- ---- outbox (transactional event outbox) ---------------------
-- Optional but typically paired with auth: lets state mutations enqueue
-- events in the same transaction as the mutation. A worker picks
-- pending rows with FOR UPDATE SKIP LOCKED and fans them out to hooks.
CREATE TABLE IF NOT EXISTS __DB_SCHEMA__.outbox (
  id                BIGSERIAL PRIMARY KEY,
  event_uuid        UUID NOT NULL UNIQUE,
  event_type        TEXT NOT NULL,
  payload           JSONB NOT NULL,
  status            TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','delivered','failed','dead')),
  attempts          INT  NOT NULL DEFAULT 0,
  next_attempt_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_error        TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  delivered_at      TIMESTAMPTZ
);

COMMENT ON TABLE __DB_SCHEMA__.outbox IS
  'Transactional outbox. Worker fans events out to hook plugins with retry+backoff.';

-- Hot path: pending rows ready to attempt now.
CREATE INDEX IF NOT EXISTS outbox_pending_ready
  ON __DB_SCHEMA__.outbox (next_attempt_at)
  WHERE status = 'pending';
